import ShockPy.shock_wave_compression.material_database.baseclass
import ShockPy.shock_wave_compression.material_database.data


from ShockPy.shock_wave_compression.material_database.baseclass import *
from ShockPy.shock_wave_compression.material_database.data import *
from ShockPy.shock_wave_compression.material_database.Kapton import Kapton
from ShockPy.shock_wave_compression.material_database.MgO import MgO
from ShockPy.shock_wave_compression.material_database.Quartz import Quartz
